#!/usr/bin/env ruby

require 'pry'
require 'json'
require 'yaml'
require './foremonkey.rb'
require './config.rb'



if __FILE__ == $0
  #Pry.config.prompt = proc { |obj, nest_level, _| "#{obj.path}:#{nest_level}> " }
  Pry.config.print = proc { |output,value| output.puts value.to_s }
  api=S6api.new(Config::CONNECTIONS[:stdconf])
  api.pry
end
